os: osx
language: swift
osx_image: xcode11

before_install:
  - pod init
  - curl https://gist.githubusercontent.com/sbertix/2e8a618086e1bc50ba57e2cfc443a1ab/raw/fa4a0711e6443a125dc75b471d242f1cac5349fb/SwiftyInsta.podfile --output Podfile
  - pod install

env:
  matrix:
    - SCHEME='SwiftyInsta.iOS'      SDK='iphonesimulator'
    - SCHEME='SwiftyInsta.macOS'    SDK='macosx'
    - SCHEME='SwiftyInsta.tvOS'     SDK='appletvsimulator'
    - SCHEME='SwiftyInsta.watchOS'  SDK='watchsimulator'
script:
  - set -o pipefail
  - swiftlint
  - xcodebuild clean build -workspace SwiftyInsta.xcworkspace -scheme ${SCHEME} -sdk ${SDK} -configuration Debug | xcpretty -c
