os: osx
language: swift
osx_image: xcode11

before_install:
- pod init
- curl https://gist.githubusercontent.com/TheM4hd1/6552b8d612bacc4f8766610beb0ba266/raw/1544b8580dbe0969c374131761be9c2aecc0cc58/SwiftyInsta.podfile --output Podfile
- pod install

xcode_workspace: SwiftyInsta.xcworkspace
matrix:
  include:
    - xcode_scheme: SwiftyInsta
      xcode_sdk: iphonesimulator10.0
    - xcode_scheme: SwiftyInsta.macOS
      xcode_sdk: macosx10.12
    - xcode_scheme: SwiftyInsta.tvOS
      xcode_sdk: tvos10.0
    - xcode_scheme: SwiftyInsta.watchOS
      xcode_sdk: watchos3.0
